import { DASHBOARD_TOUR, INFO_BOX_TOUR } from "./dashboard";
import {
    MEMBERS_PENDING_TOUR,
    MEMBERS_WANTS_TO_JOIN_TOUR,
    NEW_FEATURE_TOUR,
    PAYMENTS_BULK_TOUR,
    REQUEST_TEMPLATES_TOUR,
} from "./page-tours";

export const TOURS = [
    DASHBOARD_TOUR,
    INFO_BOX_TOUR,
    MEMBERS_PENDING_TOUR,
    MEMBERS_WANTS_TO_JOIN_TOUR,
    NEW_FEATURE_TOUR,
    PAYMENTS_BULK_TOUR,
    REQUEST_TEMPLATES_TOUR,
];
